name:                harch
version:             0.1.0.0
github:              "j1r1k/harch"
license:             BSD3
author:              "Jiri Marsicek"
maintainer:          "jiri.marsicek@gmail.com"
copyright:           "2016 Jiri Marsicek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/j1r1k/harch#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- bytestring
- containers
- extra
- foldl
- optparse-applicative
- safe
- lens
- text
- time
- turtle
- uuid
- yaml
- higgledy
- barbies

library:
  source-dirs: src

executables:
  harch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - harch

tests:
  harch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - harch
